name: ecocleanproyect
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.3
  cloud_firestore: ^4.15.9
  image_picker: ^1.0.7
  firebase_storage: ^11.7.0
  url_launcher: ^6.2.6
  flutter_facebook_auth: ^6.2.0
  google_sign_in: ^6.2.1
  twitter_login: ^4.4.2
  flutter_dotenv: ^5.0.2
  provider: 
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - lib/images/

  uses-material-design: true

